//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQualify.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.AspNetUsers1 = new HashSet<AspNetUser>();
            this.AspNetUsers11 = new HashSet<AspNetUser>();
            this.AspNetUsers12 = new HashSet<AspNetUser>();
            this.AspNetUsers13 = new HashSet<AspNetUser>();
            this.ExamTypes = new HashSet<ExamType>();
            this.ExamTypes1 = new HashSet<ExamType>();
            this.ExamTypes2 = new HashSet<ExamType>();
            this.ExamTypes3 = new HashSet<ExamType>();
            this.LoggedInTrackings = new HashSet<LoggedInTracking>();
            this.LoggedInTrackings1 = new HashSet<LoggedInTracking>();
            this.Questions = new HashSet<Question>();
            this.Questions1 = new HashSet<Question>();
            this.Questions2 = new HashSet<Question>();
            this.Questions3 = new HashSet<Question>();
            this.QuestionTopics = new HashSet<QuestionTopic>();
            this.QuestionTopics1 = new HashSet<QuestionTopic>();
            this.QuestionTopics2 = new HashSet<QuestionTopic>();
            this.QuestionTopics3 = new HashSet<QuestionTopic>();
            this.StudentSubjects = new HashSet<StudentSubject>();
            this.StudentSubjects1 = new HashSet<StudentSubject>();
            this.StudentSubjects2 = new HashSet<StudentSubject>();
            this.StudentSubjects3 = new HashSet<StudentSubject>();
            this.Subjects = new HashSet<Subject>();
            this.Subjects1 = new HashSet<Subject>();
            this.Subjects2 = new HashSet<Subject>();
            this.Subjects3 = new HashSet<Subject>();
            this.Topics = new HashSet<Topic>();
            this.Topics1 = new HashSet<Topic>();
            this.Topics2 = new HashSet<Topic>();
            this.Topics3 = new HashSet<Topic>();
            this.YearlyExams = new HashSet<YearlyExam>();
            this.YearlyExams1 = new HashSet<YearlyExam>();
            this.YearlyExams2 = new HashSet<YearlyExam>();
            this.YearlyExams3 = new HashSet<YearlyExam>();
            this.StudentExams = new HashSet<StudentExam>();
            this.StudentSubjects4 = new HashSet<StudentSubject>();
            this.UserLogins = new HashSet<UserLogin>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string FullName { get; set; }
        public string ProfilePic { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public bool IsPasswordReset { get; set; }
        public int NoOfConcurrentViews { get; set; }
        public Nullable<int> CountryId { get; set; }
        public bool IsActiveUser { get; set; }
        public Nullable<System.DateTime> ExpirationDateTime { get; set; }
        public bool IsInstitutionalAccount { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers1 { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers11 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers12 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers13 { get; set; }
        public virtual AspNetUser AspNetUser4 { get; set; }
        public virtual ICollection<ExamType> ExamTypes { get; set; }
        public virtual ICollection<ExamType> ExamTypes1 { get; set; }
        public virtual ICollection<ExamType> ExamTypes2 { get; set; }
        public virtual ICollection<ExamType> ExamTypes3 { get; set; }
        public virtual ICollection<LoggedInTracking> LoggedInTrackings { get; set; }
        public virtual ICollection<LoggedInTracking> LoggedInTrackings1 { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<Question> Questions1 { get; set; }
        public virtual ICollection<Question> Questions2 { get; set; }
        public virtual ICollection<Question> Questions3 { get; set; }
        public virtual ICollection<QuestionTopic> QuestionTopics { get; set; }
        public virtual ICollection<QuestionTopic> QuestionTopics1 { get; set; }
        public virtual ICollection<QuestionTopic> QuestionTopics2 { get; set; }
        public virtual ICollection<QuestionTopic> QuestionTopics3 { get; set; }
        public virtual ICollection<StudentSubject> StudentSubjects { get; set; }
        public virtual ICollection<StudentSubject> StudentSubjects1 { get; set; }
        public virtual ICollection<StudentSubject> StudentSubjects2 { get; set; }
        public virtual ICollection<StudentSubject> StudentSubjects3 { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
        public virtual ICollection<Subject> Subjects1 { get; set; }
        public virtual ICollection<Subject> Subjects2 { get; set; }
        public virtual ICollection<Subject> Subjects3 { get; set; }
        public virtual ICollection<Topic> Topics { get; set; }
        public virtual ICollection<Topic> Topics1 { get; set; }
        public virtual ICollection<Topic> Topics2 { get; set; }
        public virtual ICollection<Topic> Topics3 { get; set; }
        public virtual ICollection<YearlyExam> YearlyExams { get; set; }
        public virtual ICollection<YearlyExam> YearlyExams1 { get; set; }
        public virtual ICollection<YearlyExam> YearlyExams2 { get; set; }
        public virtual ICollection<YearlyExam> YearlyExams3 { get; set; }
        public virtual ICollection<StudentExam> StudentExams { get; set; }
        public virtual ICollection<StudentSubject> StudentSubjects4 { get; set; }
        public virtual ICollection<UserLogin> UserLogins { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
