//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQualify.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.QuestionTopics = new HashSet<QuestionTopic>();
            this.QuestionTopics1 = new HashSet<QuestionTopic>();
            this.StudentExamDetails = new HashSet<StudentExamDetail>();
            this.StudentExamDetails1 = new HashSet<StudentExamDetail>();
            this.YearlyExamQuestions = new HashSet<YearlyExamQuestion>();
            this.YearlyExamQuestions1 = new HashSet<YearlyExamQuestion>();
        }
    
        public int Id { get; set; }
        public string QuestionData { get; set; }
        public Nullable<int> NoOfOptions { get; set; }
        public string CorrectAnswer { get; set; }
        public string Reason { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual ICollection<QuestionTopic> QuestionTopics { get; set; }
        public virtual ICollection<QuestionTopic> QuestionTopics1 { get; set; }
        public virtual ICollection<StudentExamDetail> StudentExamDetails { get; set; }
        public virtual ICollection<StudentExamDetail> StudentExamDetails1 { get; set; }
        public virtual ICollection<YearlyExamQuestion> YearlyExamQuestions { get; set; }
        public virtual ICollection<YearlyExamQuestion> YearlyExamQuestions1 { get; set; }
    }
}
