//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQualify.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExamDetail
    {
        public int Id { get; set; }
        public Nullable<int> StudentExamId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string SelectedAnswer { get; set; }
        public string CorrectAnswer { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Question Question1 { get; set; }
        public virtual StudentExam StudentExam { get; set; }
        public virtual StudentExam StudentExam1 { get; set; }
    }
}
