//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQualify.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExam
    {
        public StudentExam()
        {
            this.StudentExamDetails = new HashSet<StudentExamDetail>();
            this.StudentExamDetails1 = new HashSet<StudentExamDetail>();
            this.StudentTopicalExams = new HashSet<StudentTopicalExam>();
            this.StudentTopicalExams1 = new HashSet<StudentTopicalExam>();
            this.StudentYearlyExams = new HashSet<StudentYearlyExam>();
            this.StudentYearlyExams1 = new HashSet<StudentYearlyExam>();
        }
    
        public int Id { get; set; }
        public string StudentId { get; set; }
        public Nullable<int> ExamTypeId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<System.DateTime> ExamDateTime { get; set; }
        public Nullable<int> TotalQuestions { get; set; }
        public Nullable<int> CorrectAnswers { get; set; }
        public Nullable<int> WrongAnswers { get; set; }
        public Nullable<double> MarksObtained { get; set; }
        public Nullable<double> Percentage { get; set; }
        public Nullable<int> TimeTaken { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ExamType ExamType { get; set; }
        public virtual ExamType ExamType1 { get; set; }
        public virtual ICollection<StudentExamDetail> StudentExamDetails { get; set; }
        public virtual ICollection<StudentExamDetail> StudentExamDetails1 { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Subject Subject1 { get; set; }
        public virtual ICollection<StudentTopicalExam> StudentTopicalExams { get; set; }
        public virtual ICollection<StudentTopicalExam> StudentTopicalExams1 { get; set; }
        public virtual ICollection<StudentYearlyExam> StudentYearlyExams { get; set; }
        public virtual ICollection<StudentYearlyExam> StudentYearlyExams1 { get; set; }
    }
}
