//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQualify.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTopicalExam
    {
        public int Id { get; set; }
        public Nullable<int> StudentExamId { get; set; }
        public Nullable<int> TopicId { get; set; }
    
        public virtual StudentExam StudentExam { get; set; }
        public virtual StudentExam StudentExam1 { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual Topic Topic1 { get; set; }
    }
}
