//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQualify.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.QuestionTopics = new HashSet<QuestionTopic>();
            this.QuestionTopics1 = new HashSet<QuestionTopic>();
            this.StudentTopicalExams = new HashSet<StudentTopicalExam>();
            this.StudentTopicalExams1 = new HashSet<StudentTopicalExam>();
        }
    
        public int Id { get; set; }
        public int SubjectId { get; set; }
        public string Name { get; set; }
        public string TopicDescription { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual ICollection<QuestionTopic> QuestionTopics { get; set; }
        public virtual ICollection<QuestionTopic> QuestionTopics1 { get; set; }
        public virtual ICollection<StudentTopicalExam> StudentTopicalExams { get; set; }
        public virtual ICollection<StudentTopicalExam> StudentTopicalExams1 { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Subject Subject1 { get; set; }
    }
}
