//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQualify.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.StudentExams = new HashSet<StudentExam>();
            this.UserLogins = new HashSet<UserLogin>();
            this.UserSubjects = new HashSet<UserSubject>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<StudentExam> StudentExams { get; set; }
        public virtual ICollection<UserLogin> UserLogins { get; set; }
        public virtual ICollection<UserSubject> UserSubjects { get; set; }
    }
}
