//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQualify.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearlyExam
    {
        public YearlyExam()
        {
            this.StudentYearlyExams = new HashSet<StudentYearlyExam>();
            this.StudentYearlyExams1 = new HashSet<StudentYearlyExam>();
            this.YearlyExamQuestions = new HashSet<YearlyExamQuestion>();
            this.YearlyExamQuestions1 = new HashSet<YearlyExamQuestion>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> ExamYear { get; set; }
        public Nullable<int> ExamMonth { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<double> AGradePercent { get; set; }
        public Nullable<double> BGradePercent { get; set; }
        public Nullable<double> CGradePercent { get; set; }
        public Nullable<double> DGradePercent { get; set; }
        public Nullable<double> EGradePercent { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual ICollection<StudentYearlyExam> StudentYearlyExams { get; set; }
        public virtual ICollection<StudentYearlyExam> StudentYearlyExams1 { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Subject Subject1 { get; set; }
        public virtual ICollection<YearlyExamQuestion> YearlyExamQuestions { get; set; }
        public virtual ICollection<YearlyExamQuestion> YearlyExamQuestions1 { get; set; }
    }
}
