//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQualify.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearlyExamQuestion
    {
        public int Id { get; set; }
        public Nullable<int> YearlyExamId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> QuestionOrder { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Question Question1 { get; set; }
        public virtual YearlyExam YearlyExam { get; set; }
        public virtual YearlyExam YearlyExam1 { get; set; }
    }
}
